name: SafeRandomTeleport
version: 0.8
author: Blautee, Trebtee
api-version: 1.19
softdepend:
 - Multiverse-Core

main: de.trebtee.srtp.main.Main
description: A pvp-compatible, safe random teleport plugin!
commands:
  srtp:
    description: Safe Random Teleport
